<a href="https://colab.research.google.com/github/Poonguzhali0409/Assignments/blob/main/Numpy_Panndas_Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **2D array (print dimension and shape)**

In [3]:
import numpy as np
import pandas as pd


arr =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Dimension : ',arr.ndim)
print('Shape : ',arr.shape)

Dimension :  2
Shape :  (2, 5)


#### **array of 20 numbers using arange function and slice the values between 10 to 15 **bold text**


In [9]:
num = np.array ([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(num[9:15])

[10 11 12 13 14 15]


#### **create two array and perform mathematical operation**

In [21]:
x = np.random.random((7,5))
y = np.random.random((7,5))
print('X --- > ' ,x)
print('Y --- > ',y)
print('Addition : ',x+y)
print('Subtraction : ',x-y)
print('Multiplication : ',x*y)
print('Division : ',x/y)
x

X --- >  [[0.94347872 0.64137252 0.29845651 0.07393899 0.55637471]
 [0.62068179 0.81638706 0.26053175 0.88367837 0.62949245]
 [0.89779731 0.12341228 0.18041667 0.90914559 0.20891923]
 [0.40656113 0.52842136 0.36547388 0.44996675 0.85399741]
 [0.20603187 0.75535127 0.94425802 0.23934969 0.96358326]
 [0.11058269 0.15398928 0.69447137 0.1033689  0.31067791]
 [0.58352778 0.20339461 0.18382416 0.58808815 0.45737712]]
Y --- >  [[0.93138866 0.37740841 0.46613714 0.5908558  0.3201817 ]
 [0.7469082  0.59440651 0.44771733 0.52143409 0.96798733]
 [0.02607462 0.46964117 0.22620342 0.98553452 0.44237606]
 [0.80256033 0.35634557 0.98767623 0.73788831 0.47386938]
 [0.43700347 0.26809012 0.27436174 0.1078563  0.73175255]
 [0.80203773 0.28081787 0.24714482 0.8481513  0.59145764]
 [0.64718923 0.17173906 0.29050795 0.27569783 0.95524578]]
Addition :  [[1.87486738 1.01878093 0.76459365 0.66479479 0.87655642]
 [1.36759    1.41079357 0.70824908 1.40511246 1.59747978]
 [0.92387193 0.59305345 0.40662009 1.894

array([[0.94347872, 0.64137252, 0.29845651, 0.07393899, 0.55637471],
       [0.62068179, 0.81638706, 0.26053175, 0.88367837, 0.62949245],
       [0.89779731, 0.12341228, 0.18041667, 0.90914559, 0.20891923],
       [0.40656113, 0.52842136, 0.36547388, 0.44996675, 0.85399741],
       [0.20603187, 0.75535127, 0.94425802, 0.23934969, 0.96358326],
       [0.11058269, 0.15398928, 0.69447137, 0.1033689 , 0.31067791],
       [0.58352778, 0.20339461, 0.18382416, 0.58808815, 0.45737712]])

#### **Create 2 incompatible arrays for broadcast and print out the error**

In [18]:
x = np.random.random((7,5))
y = np.random.random((6,5))
print('Addition : ',x+y)


ValueError: ignored

#### **Create two arrays of any dimension and perform vstack and hstack**

In [25]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
print('vstack : ',np.vstack((a,b)) )
print('hstack : ',np.hstack((a,b)) )

vstack :  [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack :  [[1 2 5 6]
 [3 4 7 8]]


#### **Append two arrays using axis = 0 and axis = 1**

In [31]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
c= np.append(a,b,axis=0)
d = np.append(a,b,axis=1)
print(c)
print(d)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


#### **Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation**

In [6]:
list2 = [['carrot',30,'1 kg',101],['Tomato',20,'2 kg',201],['Onion',50,'1 kg',301],['Corn',70,'1 Nos',301],['Raddish',70,'1/2 kg',401],
         
         ['bitterguard',70,'1 kg',501],
         ['Corn',70,'1 Nos',301],['Corn',70,'1 Nos',301]]
final = pd.DataFrame(list2,columns=['Veggies','Price','Quantity','Item id'])
(final)

Veggies  Price Quantity  Item id
0       carrot     30     1 kg      101
1       Tomato     20     2 kg      201
2        Onion     50     1 kg      301
3         Corn     70    1 Nos      301
4      Raddish     70   1/2 kg      401
5  bitterguard     70     1 kg      501
6         Corn     70    1 Nos      301
7         Corn     70    1 Nos      301

#### **Create a dataframe of 4 X 8 dimension using a dictionary**




In [5]:
xx = {'age':[25,26,26,23,30,27,29],'name':['Tom','James','Ricky','Vin','Steve','Smith','Jack'],'rating':[4.23,3.24,3.98,2.56,3.20,4.60,3.80]}
df=pd.DataFrame(xx)
df.T

0      1      2     3      4      5     6
age       25     26     26    23     30     27    29
name     Tom  James  Ricky   Vin  Steve  Smith  Jack
rating  4.23   3.24   3.98  2.56    3.2    4.6   3.8

#### **Use loc and ilocto subset the data for the above dataframe**

In [18]:
print(df.loc[:3,['age','name']])
print(df.iloc[0:3])

   age   name
0   25    Tom
1   26  James
2   26  Ricky
3   23    Vin
   age   name  rating
0   25    Tom    4.23
1   26  James    3.24
2   26  Ricky    3.98


#### **How to check the total number of not null values in a column?**




In [20]:
df1 = pd.DataFrame(np.random.randn(5,3), index = ['a','c','e','f','h'], columns= ['One', 'Two', 'Three'])
print (df1)
print (df1['One'].notnull().sum())

        One       Two     Three
a  0.530920 -0.059963  0.234623
c -0.955570  0.290335  0.235134
e  0.268479  1.061289 -1.780590
f  0.831319 -0.096642  0.613571
h  0.152987 -0.345457 -0.952921
5


#### **Create a dataframe with missing values and fill them all with 100**

In [27]:
x = np.array([[0.94347872, np.nan , 0.29845651, 0.07393899, 0.55637471],
       [0.62068179, 0.81638706, 0.26053175, 0.88367837, 0.62949245],
       [0.89779731, 0.12341228, 0.18041667, 0.90914559, 0.20891923],
       [0.40656113, 0.52842136, 0.36547388, 0.44996675, 0.85399741],
       [0.20603187, 0.75535127, 0.94425802, 0.23934969, 0.96358326],
       [0.11058269, 0.15398928, np.nan, 0.1033689 , 0.31067791],
       [0.58352778, 0.20339461, 0.18382416, 0.58808815,np.nan]])
df = pd.DataFrame (x )
print(df.fillna(100))

          0           1           2         3           4
0  0.943479  100.000000    0.298457  0.073939    0.556375
1  0.620682    0.816387    0.260532  0.883678    0.629492
2  0.897797    0.123412    0.180417  0.909146    0.208919
3  0.406561    0.528421    0.365474  0.449967    0.853997
4  0.206032    0.755351    0.944258  0.239350    0.963583
5  0.110583    0.153989  100.000000  0.103369    0.310678
6  0.583528    0.203395    0.183824  0.588088  100.000000


#### **Create a dataframe with missing values and drop the null records**

In [31]:
y = np.array([[0.94347872, np.nan , 0.29845651, 0.07393899, 0.55637471],
       [0.62068179, 0.81638706, 0.26053175, 0.88367837, 0.62949245],
       [0.89779731, 0.12341228, 0.18041667, 0.90914559, 0.20891923],
       [0.40656113, 0.52842136, 0.36547388, 0.44996675, 0.85399741],
       [0.20603187, 0.75535127, 0.94425802, 0.23934969, 0.96358326],
       [0.11058269, 0.15398928, np.nan, 0.1033689 , 0.31067791],
       [0.58352778, 0.20339461, 0.18382416, 0.58808815,np.nan]])
df = pd.DataFrame (y )

df.dropna()

0         1         2         3         4
1  0.620682  0.816387  0.260532  0.883678  0.629492
2  0.897797  0.123412  0.180417  0.909146  0.208919
3  0.406561  0.528421  0.365474  0.449967  0.853997
4  0.206032  0.755351  0.944258  0.239350  0.963583

#### **Final task**

In [43]:
hair =  pd.DataFrame([[25,'Black','SW',1],
                        [30,'Black','NW',1],
                        [45,'Red','NE',1],
                        [35,'Blond','SW',0],
                        [33,'Brown','SW',0],
                        [35,'Brown','NE',0],
                        [25,'Black','SW',0],
                        [52,'Brown','SE',0],
                        [21,'Blond','SW',1],
                        [24,'Blond','NE',0],
                        [48,'Black','SW',1],
                        [22,'Black','SW',0],
                        [27,'Brown','NE',0],
                        [28,'Black','SE',1],
                        [21,'Blond','SE',1],
                        [51,'Black','NW',0],
                        [23,'Brown','SE',1],                        
                       ]
                       ,columns =['AGE','HAIR COLOR','US REGION','VALIDATION'] )
hair.groupby(['US REGION'])['AGE'].count()

US REGION
NE    4
NW    2
SE    4
SW    7
Name: AGE, dtype: int64

In [48]:
hair.groupby(['HAIR COLOR'])['AGE','VALIDATION'].sum().reset_index()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.


AGE  VALIDATION
HAIR COLOR                 
Black       229           4
Blond       101           2
Brown       170           1
Red          45           1

In [50]:
hair.groupby(['US REGION'])['AGE'].mean()

US REGION
NE    32.750000
NW    40.500000
SE    31.000000
SW    29.857143
Name: AGE, dtype: float64

In [51]:
hair.groupby(['US REGION'])['AGE'].median()

US REGION
NE    31.0
NW    40.5
SE    25.5
SW    25.0
Name: AGE, dtype: float64

#### **SPLIT**

In [59]:
lefftt = hair.iloc[:9]
righttt = hair.iloc[9:]
print(pd.merge(lefftt, righttt, on='US REGION'))
print(lefftt)
print (righttt)

    AGE_x HAIR COLOR_x US REGION  VALIDATION_x  AGE_y HAIR COLOR_y  \
0      25        Black        SW             1     48        Black   
1      25        Black        SW             1     22        Black   
2      35        Blond        SW             0     48        Black   
3      35        Blond        SW             0     22        Black   
4      33        Brown        SW             0     48        Black   
5      33        Brown        SW             0     22        Black   
6      25        Black        SW             0     48        Black   
7      25        Black        SW             0     22        Black   
8      21        Blond        SW             1     48        Black   
9      21        Blond        SW             1     22        Black   
10     30        Black        NW             1     51        Black   
11     45          Red        NE             1     24        Blond   
12     45          Red        NE             1     27        Brown   
13     35        Bro

In [58]:
new = lefftt.merge(righttt, how='right',on='US REGION')
new

AGE_x HAIR COLOR_x US REGION  VALIDATION_x  AGE_y HAIR COLOR_y  \
0      45          Red        NE             1     24        Blond   
1      35        Brown        NE             0     24        Blond   
2      25        Black        SW             1     48        Black   
3      35        Blond        SW             0     48        Black   
4      33        Brown        SW             0     48        Black   
5      25        Black        SW             0     48        Black   
6      21        Blond        SW             1     48        Black   
7      25        Black        SW             1     22        Black   
8      35        Blond        SW             0     22        Black   
9      33        Brown        SW             0     22        Black   
10     25        Black        SW             0     22        Black   
11     21        Blond        SW             1     22        Black   
12     45          Red        NE             1     27        Brown   
13     35        Brown        NE             0     27        Brown   
14     52        Brown        SE             0     28        Black   
15     52        Brown        SE             0     21        Blond   
16     30        Black        NW             1     51        Black   
17     52        Brown        SE             0     23        Brown   

    VALIDATION_y  
0              0  
1              0  
2              1  
3              1  
4              1  
5              1  
6              1  
7              0  
8              0  
9              0  
10             0  
11             0  
12             0  
13             0  
14             1  
15             1  
16             0  
17             1

In [55]:
new1 = lefftt.merge(righttt, how='left',on='US REGION')
new1

AGE_x HAIR COLOR_x US REGION  VALIDATION_x  AGE_y HAIR COLOR_y  \
0      25        Black        SW             1     48        Black   
1      25        Black        SW             1     22        Black   
2      30        Black        NW             1     51        Black   
3      45          Red        NE             1     27        Brown   
4      35        Blond        SW             0     48        Black   
5      35        Blond        SW             0     22        Black   
6      33        Brown        SW             0     48        Black   
7      33        Brown        SW             0     22        Black   
8      35        Brown        NE             0     27        Brown   
9      25        Black        SW             0     48        Black   
10     25        Black        SW             0     22        Black   
11     52        Brown        SE             0     28        Black   
12     52        Brown        SE             0     21        Blond   
13     52        Brown        SE             0     23        Brown   
14     21        Blond        SW             1     48        Black   
15     21        Blond        SW             1     22        Black   
16     24        Blond        NE             0     27        Brown   

    VALIDATION_y  
0              1  
1              0  
2              0  
3              0  
4              1  
5              0  
6              1  
7              0  
8              0  
9              1  
10             0  
11             1  
12             1  
13             1  
14             1  
15             0  
16             0

#### **Split the below table and perform concat row wise and column wise**

In [60]:
neww = pd.concat ([lefftt,righttt])

In [61]:
neww

AGE HAIR COLOR US REGION  VALIDATION
0    25      Black        SW           1
1    30      Black        NW           1
2    45        Red        NE           1
3    35      Blond        SW           0
4    33      Brown        SW           0
5    35      Brown        NE           0
6    25      Black        SW           0
7    52      Brown        SE           0
8    21      Blond        SW           1
9    24      Blond        NE           0
10   48      Black        SW           1
11   22      Black        SW           0
12   27      Brown        NE           0
13   28      Black        SE           1
14   21      Blond        SE           1
15   51      Black        NW           0
16   23      Brown        SE           1

In [63]:
neww = pd.concat ([lefftt,righttt],axis=1)

In [64]:
neww

AGE HAIR COLOR US REGION  VALIDATION   AGE HAIR COLOR US REGION  \
0   25.0      Black        SW         1.0   NaN        NaN       NaN   
1   30.0      Black        NW         1.0   NaN        NaN       NaN   
2   45.0        Red        NE         1.0   NaN        NaN       NaN   
3   35.0      Blond        SW         0.0   NaN        NaN       NaN   
4   33.0      Brown        SW         0.0   NaN        NaN       NaN   
5   35.0      Brown        NE         0.0   NaN        NaN       NaN   
6   25.0      Black        SW         0.0   NaN        NaN       NaN   
7   52.0      Brown        SE         0.0   NaN        NaN       NaN   
8   21.0      Blond        SW         1.0   NaN        NaN       NaN   
9    NaN        NaN       NaN         NaN  24.0      Blond        NE   
10   NaN        NaN       NaN         NaN  48.0      Black        SW   
11   NaN        NaN       NaN         NaN  22.0      Black        SW   
12   NaN        NaN       NaN         NaN  27.0      Brown        NE   
13   NaN        NaN       NaN         NaN  28.0      Black        SE   
14   NaN        NaN       NaN         NaN  21.0      Blond        SE   
15   NaN        NaN       NaN         NaN  51.0      Black        NW   
16   NaN        NaN       NaN         NaN  23.0      Brown        SE   

    VALIDATION  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          NaN  
9          0.0  
10         1.0  
11         0.0  
12         0.0  
13         1.0  
14         1.0  
15         0.0  
16         1.0