<a href="https://colab.research.google.com/github/Poonguzhali0409/Assignments/blob/main/Test_1_(13_march).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### **Question 1 [get input - print years]**

In [1]:
name = input('Enter your name : ')
age = int(input('Enter your age : '))
birthyear = 2022-age
result = birthyear+100
print('Hi ',name,' You will be 100 years in ',result)

Enter your name : vj
Enter your age : 33
Hi  vj  You will be 100 years in  2088


##### **Question 2 [Pandas groupby]**

In [15]:
import pandas as pd 

d1 = {'Subjects':['Science','Maths','Social','English'],'Max Mark':[100,100,100,100]}
df2 = pd.DataFrame(d1)
df2['Min Mark']= pd.Series([40,40,40,40])
df2.groupby('Max Mark').groups


{100: [0, 1, 2, 3]}

##### **Question 3 [DataFrame from list]**

In [11]:
list2 = [['carrot',30],['Tomato',20],['Onion',50]]
final = pd.DataFrame(list2,columns=['Veggies','Price'])
(final)

Veggies  Price
0  carrot     30
1  Tomato     20
2   Onion     50

##### **Question 4 [combine the dataframe in pandas]**



In [16]:
# using series

d1 = {'Subjects':['Science','Maths','Social','English'],'Max Mark':[100,100,100,100]}
df2 = pd.DataFrame(d1)
df2['Min Mark']= pd.Series([40,40,40,40])
print(df2)

#using append

dic1 ={'Name':['Poojitha','Pranav','Nithya','Umer'],'Age':[10,13,12,20],'Class':['B.E','B.TECH','B.E','B.E']}
list1=pd.DataFrame(dic1)
dic2 ={'Name':['Riyas','Sethu','Mukesh','Abarna'],'Age':[11,14,11,10],'Class':['MCA','PHD','BE','B.TECH']}
list2=pd.DataFrame(dic2,index=[4,5,6,7])
dic3 = list1.append(list2)
dic3

  Subjects  Max Mark  Min Mark
0  Science       100        40
1    Maths       100        40
2   Social       100        40
3  English       100        40


Name  Age   Class
0  Poojitha   10     B.E
1    Pranav   13  B.TECH
2    Nithya   12     B.E
3      Umer   20     B.E
4     Riyas   11     MCA
5     Sethu   14     PHD
6    Mukesh   11      BE
7    Abarna   10  B.TECH

##### **Question 5 [difference between list and tuples in Python]**

In [4]:
list2 = [['mutable','Immutable'],['useful for insertion and deletion','useful for accessing data']]
final = pd.DataFrame(list2,columns=['List','Tuple'],index = [1,2])
(final)

List                      Tuple
1                            mutable                  Immutable
2  useful for insertion and deletion  useful for accessing data

##### **Question 6 [mean,median,mode]**

In [26]:
import numpy as np

num = np.array([1,5,3,100,4,48])
print('median : ',np.median (num))
print('mean : ',np.mean (num))
print('Standar Deviation : ',np.std (num))

median :  4.5
mean :  26.833333333333332
Standar Deviation :  36.59424666377065


##### **Question 7 [remove duplicate element from list]** 

In [29]:
list1 = [1,2,3,4,'aa','bb',1,'cc','aa']
result = list(set(list1))
result

[1, 2, 3, 4, 'cc', 'aa', 'bb']

##### **Question 8 [map () in python]** 

In [5]:
#used to map a specific math fun to the list

imlist = [2,6,4,7,5]
newlist = list(map(lambda x : x*2,imlist))
print(newlist)

[4, 12, 8, 14, 10]


##### **Question 9 [pass in python]** 

In [6]:
x = [5,7,6]
for i in x :
  pass

##### **Question 10 [vstack in python]** 

In [39]:
from numpy.ma.core import ndim
#to get the array veritically

a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[7,8,9],[10,11,12]])
print (np.stack((a1,a2)))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
