In [191]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

from sklearn.metrics import mean_squared_error, r2_score

from sklearn.model_selection import train_test_split

In [192]:
train = pd.read_csv(r'C:\Users\COMPUER\Desktop\DataScience\vehicle insurance hackathon\train.csv')
test = pd.read_csv(r'C:\Users\COMPUER\Desktop\DataScience\vehicle insurance hackathon\test.csv')
sample= pd.read_csv(r'C:\Users\COMPUER\Desktop\DataScience\vehicle insurance hackathon\sample_submission.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\COMPUER\\Desktop\\DataScience\\vehicle insurance hackathon\\sample_submission.csv'

In [ ]:
train

In [ ]:
train.describe(include='all').T

In [ ]:
train['Age'].nunique()

In [ ]:
train[:5]

In [ ]:
train['Vehicle_Damage'].value_counts()

In [ ]:
train.isnull().sum()


In [ ]:
catColumns = ['Gender', 'Vehicle_Damage','Vehicle_Age']
train_dum = pd.get_dummies(train, columns = catColumns)
train_dum.head()

In [ ]:
train_dum['Age_bins'] = pd.cut(x=train_dum['Age'], bins=[20, 30, 40, 50,60,70,80,85])

In [ ]:
train_dum.head()

In [ ]:
train_dum['Age_bins'].nunique()

In [ ]:
catColumns = ['Age_bins']
train_dum = pd.get_dummies(train_dum, columns = catColumns)
train_dum.head()

In [ ]:
train_dum.columns

In [ ]:
train_dum.head()

In [ ]:
train_dum['Region_Code'].nunique()

In [ ]:
train_dum['Vintage'].min()

In [ ]:
train_dum['Vintage'].max()

In [ ]:
train_dum.head()


In [ ]:
train_dum['Vintage'].min()

In [ ]:
train_dum['Vintage'].nunique()

In [ ]:
train_dum['Vintage_bins'] = pd.cut(x=train_dum['Vintage'], bins=[10,60,90,120,150,180,210,240,270,300])

In [ ]:
train_dum['Vintage_bins'].value_counts()

In [ ]:
train_dum

In [ ]:
catColumns = ['Vintage_bins']
train_dum = pd.get_dummies(train_dum, columns = catColumns)
train_dum.head()

In [ ]:
train_dum['Annual_Premium'].value_counts()

In [ ]:
 train_dum['Annual_Premium'] =[1 if x== 2630 else 0 for x in train_dum['Annual_Premium']]

In [ ]:
train_dum['Annual_Premium'].value_counts()

In [ ]:
catColumns = ['Region_Code']
train_dum = pd.get_dummies(train_dum, columns = catColumns)
train_dum.head()


In [ ]:
train_dum.columns


In [ ]:
catColumns = ['Gender', 'Vehicle_Damage','Vehicle_Age']
test_dum = pd.get_dummies(test, columns = catColumns)
test_dum.head()

In [ ]:
test_dum['Age_bins'] = pd.cut(x=test_dum['Age'], bins=[20, 30, 40, 50,60,70,80,85])

In [ ]:
test_dum = pd.get_dummies(test_dum, columns = ['Age_bins'])
test_dum.head()

In [ ]:
test_dum['Vintage_bins'] = pd.cut(x=test_dum['Vintage'], bins=[10,60,90,120,150,180,210,240,270,300])
test_dum.head()

In [ ]:
 test_dum['Annual_Premium'] =[1 if x== 2630 else 0 for x in test_dum['Annual_Premium']]

In [ ]:
catColumns = ['Vintage_bins']
test_dum = pd.get_dummies(test_dum, columns = catColumns)
test_dum.head()

In [ ]:
test_dum['Annual_Premium'].value_counts()

In [ ]:
train_preprocessed = train_dum.drop(columns=['id','Age','Policy_Sales_Channel','Vintage'])
test_preprocessed = test_dum.drop(columns=['id','Age','Policy_Sales_Channel','Vintage'])

In [ ]:
train_preprocessed.to_csv("train_preprocessed.csv", index = False)
test_preprocessed.to_csv("test_preprocessed.csv", index = False)

In [ ]:
test_preprocessed.columns

In [193]:
train_mo = pd.read_csv("train_preprocessed.csv")
test_mo = pd.read_csv("test_preprocessed.csv")
sample = pd.read_csv("sample_submission_veh.csv")

In [ ]:
sample

In [194]:
X = train_mo.drop(columns = 'Response')
y = train_mo['Response']

In [195]:
train_X, test_X, train_y, test_y = train_test_split(X,y, test_size = 0.2, random_state=32)


In [196]:
model = LinearRegression()
model.fit(train_X, train_y)

LinearRegression()

In [166]:
model.coef_

array([ 1.48794432e-14,  6.76264600e-14,  3.49720253e-15,  1.00000000e+00,
       -2.52492994e-01, -2.52492994e-01,  1.59071941e-01,  1.59071941e-01,
        4.09475721e-02,  4.09475721e-02,  4.09475721e-02, -3.67761377e-16,
       -4.99600361e-16,  1.11022302e-16,  3.33066907e-16,  6.66133815e-16,
       -5.55111512e-16,  7.49400542e-16,  9.71445147e-17, -2.91433544e-16,
       -4.16333634e-17, -6.93889390e-16, -3.01841885e-16,  1.45283091e-16,
       -5.29090660e-17, -3.12250226e-16,  3.31332184e-16, -8.75122758e-02,
       -8.75122758e-02, -8.75122758e-02, -8.75122758e-02, -8.75122758e-02,
       -8.75122758e-02, -8.75122758e-02, -8.75122758e-02, -8.75122758e-02,
       -8.75122758e-02, -8.75122758e-02, -8.75122758e-02, -8.75122758e-02,
       -8.75122758e-02, -8.75122758e-02, -8.75122758e-02, -8.75122758e-02,
       -8.75122758e-02, -8.75122758e-02, -8.75122758e-02, -8.75122758e-02,
       -8.75122758e-02, -8.75122758e-02, -8.75122758e-02, -8.75122758e-02,
       -8.75122758e-02, -

In [197]:
model.intercept_


-4408440031.005305

In [206]:
train_X_pred = model.predict(train_X)
test_X_pred = model.predict(test_X)
train_X_pred
test_X_pred

array([-0.06900311,  0.34083271,  0.31942081, ...,  0.08939648,
        0.01029968, -0.01637268])

In [199]:
train_X_RMSE = np.sqrt(mean_squared_error(train_y, train_X_pred))
test_X_RMSE = np.sqrt(mean_squared_error(test_y, test_X_pred))

print("Train RMSE : ",train_X_RMSE)
print("Test RMSE : ",test_X_RMSE)

Train RMSE :  0.30139344177351163
Test RMSE :  0.30029419439219146


In [263]:
train_X_R2 = r2_score(train_y, train_X_pred)
test_X_R2 = r2_score(test_y, test_X_pred)

In [264]:
print("Train R2 : ",train_X_R2)
print("Test R2 : ",test_X_R2)

Train R2 :  0.1576098461813512
Test R2 :  0.15223902755891117


In [239]:
test_pred = model.predict(test_mo)

In [252]:
test_pred_modified = np.where(test_pred<0,0,1)

test_pred_modified

array([0, 0, 0, ..., 0, 0, 0])

array([0., 0., 0., ..., 0., 0., 0.])

In [256]:
test['Response'] = test_pred_modified


In [258]:
output = test[[ "id", "Response"]]

In [260]:
output['Response'].value_counts()


0    114011
1     13026
Name: Response, dtype: int64

In [262]:
output.to_csv("result_vechile.csv", index = False)
